### ISSUE TITLE
create a lattice from a set of points

### ISSUE THREAD

**Issue by GeorgesSadaka** [alexkaz2/hexalattice#4]
Hello,
using the following script :

```
from hexalattice.hexalattice import *
hex_centers, _ = create_hex_grid(nx=5,ny=5,do_plot=True)
tile_centers_x = hex_centers[:, 0]
tile_centers_y = hex_centers[:, 1]
from scipy.spatial import Delaunay
points=np.array([tile_centers_x,tile_centers_y]);
points=points.T
tri = Delaunay(points)
plt.triplot(points[:,0], points[:,1], tri.simplices)
plt.show()
```
we obtain the result at the left of the attached image
<img width="1221" alt="Capture d’écran 2021-06-08 à 15 57 11" src="https://user-images.githubusercontent.com/40874021/121199049-e3e20700-c872-11eb-9578-f29daef60854.png">

is it possible to create the lattice (pentagone, hexagone, heptagone or more) around points that are not equidistant ?(as in the right of the attached image) knowing only one information which is the coordinate of the center of the lattice ?
thanks in advance

**Comment by alexkaz2** [comment]
Hi Georges,
Hexalattice produces only hexagonal grids with all hexagons intact. You can expand this functionality for your needs by the following simple steps:
- Obtaining the hexagon centers from hexalattice:    >> hex_centers, _ = create_hex_grid(nx=5,ny=5,do_plot=True);
- Keeping only a sub-set of hexagons:     >> hex_centers_subset = hex_centers[my_boolean_filter]
- Manually plotting the kept hexagons:    >> [copy these lines from [hexlattice internals]](https://github.com/alexkaz2/hexalattice/blob/57c6edd5baeda36e49f5119db45b27beb5fb4698/hexalattice/hexalattice.py#L136)

This will produce the output to the right.
I hope this helps...
Alex

**Comment by GeorgesSadaka** [comment]
Thanks Alex for your reply,
following your recommendation, the following script :
```
tile_centers_x = hex_centers[:, 0]
tile_centers_y = hex_centers[:, 1]
my_boolean_filter = tile_centers_x % 2 == 0
hex_centers_subset = hex_centers[my_boolean_filter]
coord_x=hex_centers_subset[:, 0]
coord_y=hex_centers_subset[:, 1]
min_diam=1.
plotting_gap=0
rotate_deg=0
patches = []
for curr_x, curr_y in zip(coord_x, coord_y):
    polygon = mpatches.RegularPolygon((curr_x, curr_y), numVertices=6,
                                          radius=min_diam / np.sqrt(3) * (1 - plotting_gap),
                                          orientation=np.deg2rad(-rotate_deg))
    patches.append(polygon)
collection = PatchCollection(patches, edgecolor='k', facecolor='w')
h_ax = plot_single_lattice(coord_x, coord_y, 'k', 'w', min_diam, plotting_gap, rotate_deg)
h_ax.add_collection(collection)
points=np.array([coord_x,coord_y]);
points=points.T
tri = Delaunay(points)
h_ax.triplot(points[:,0], points[:,1], tri.simplices)
```
give :
<img width="446" alt="Capture d’écran 2021-06-09 à 00 06 15" src="https://user-images.githubusercontent.com/40874021/121263875-94bdc580-c8b6-11eb-9762-6522cc8ff4e7.png">
but unfortunately it's not what I'm looking for,
thanks any way

**Comment by alexkaz2** [comment]
This is what I've got by replacing
`my_boolean_filter = tile_centers_x % 2 == 0`
by
`my_boolean_filter = np.random.rand(tile_centers_x.shape[0]) > 0.85`
and using initial grid of 10x10 hexagons, with: `hex_centers, _ = create_hex_grid(nx=10,ny=10,do_plot=True);`

Is is close to what you are looking for?

![image](https://user-images.githubusercontent.com/6910428/121269238-22ee7780-c8c8-11eb-8e53-debfe478aafc.png)

**Comment by GeorgesSadaka** [comment]
In fact I'm looking to obtain a lattice that cover all the domain like this knowing only the coordinates of the center of each cell :
<img width="451" alt="Capture d’écran 2021-06-09 à 01 19 07" src="https://user-images.githubusercontent.com/40874021/121269805-bf148080-c8c0-11eb-9712-4771a5f215ac.png">

**Comment by alexkaz2** [comment]
I see, this is beyond the scope of hexalattice.
I would suggest looking for python implementations of Voronoi meshes, such as https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.voronoi_plot_2d.html

Sincerely,
Alex.
(Please consider closing the issue)

**Comment by GeorgesSadaka** [comment]
thank you!
```
from scipy.spatial import Voronoi, voronoi_plot_2d
vor = Voronoi(points)
voronoi_plot_2d(vor, show_vertices=False, line_colors='red',
                     line_width=2, line_alpha=0.6, point_size=2)
ax = plt.gca()
ax.axis([-10,10,-10,10])
ax.set_aspect('equal', adjustable='box')
plt.triplot(points[:,0], points[:,1], '--', color='0.')
plt.show()
```
<img width="1123" alt="Capture d’écran 2021-06-09 à 02 26 46" src="https://user-images.githubusercontent.com/40874021/121274179-41557280-c8ca-11eb-966e-14a8009b8b8f.png">
