### ISSUE TITLE
Request for ability to alter linewidth

### ISSUE THREAD

**Issue by CTAYLOR888** [alexkaz2/hexalattice#5]
Hey Alex,

Loving the hexalattice code. 

Just one note, if the lattice is large and overlaid over another image, the line width is too thick, it would be good to be able to set the linewidth parameter for the call to matplotlib.patches.RegularPolygon without having to override your code.
An example graphic (produced by passing a h_ax to create_hex_grid) below - the problem gets more and more pronounced as the number of hexes increases.
![image](https://user-images.githubusercontent.com/58879054/139844597-6bc3b193-9a6b-4bc9-8d55-b0820fe48c9a.png)

Keep up the good work

Chris

**Comment by alexkaz2** [comment]
Hi Chris (@CTAYLOR888),

Thank you for the kind words!
I updated the code to expose the line width as an argument of the 'plot_single_lattice_custom_colors()' function.
See the new graphics in [hexalattice wiki](https://github.com/alexkaz2/hexalattice/wiki/Assigning-individual-colors-to-hexagons)

Code example:

```
plot_single_lattice_custom_colors(hex_centers[:, 0], hex_centers[:, 1],
                                  face_color=colors,
                                  edge_color=colors*0,
                                  min_diam=1.,
                                  plotting_gap=0,
                                  rotate_deg=0,
                                  line_width=0.1,
                                  h_ax=h_ax)
```

**Comment by CTAYLOR888** [comment]
Thanks Alex!
Will you be updating on conda-forge - I have to use Anaconda for compatibility and consistency reasons.
Best
Chris

**Comment by alexkaz2** [comment]
Hi Chris, 
I uploaded the new version to pypi, so you can already install Hexalattice with pip.
I expect conda-forge to update its caches in several hours from now...

 I will close this issue for now, but feel free to reopen it if conda refuses to auto-update or the new version is not satisfactory for your needs :)

Alex

**Comment by CTAYLOR888** [comment]
Thanks Alex. However in my original request I mentioned that I was using create_hex_grid - could you also  expose line width as an argument for that key function?
Many thanks in advance
Chris

**Comment by alexkaz2** [comment]
@CTAYLOR888 Sure, obviously I should have changed this API as well...
I will reopen the issue until I find the cycles for this fix :)

**Comment by CTAYLOR888** [comment]
Thanks again Alex!

**Comment by alexkaz2** [comment]
Hi @CTAYLOR888,
Sorry for the late response, I added the argument to create_hex_grid as well

**Comment by CTAYLOR888** [comment]
Many thanks!
Dr. Christopher Taylor  

    On Monday, 6 March 2023 at 23:00:02 GMT, alexkaz2 ***@***.***> wrote:  
 
 


Hi @CTAYLOR888,
Sorry for the late response, I added the argument to create_hex_grid as well
