### ISSUE TITLE
back ground color adjustment

### ISSUE THREAD

**Issue by masoudrahimi39** [alexkaz2/hexalattice#7]
I want to adjust the background color. thanks for your attention.

**Comment by alexkaz2** [comment]
Hi Masoud,
Sorry for the late response, I updated the code to allow this feature.

![image](https://user-images.githubusercontent.com/6910428/223274805-edb9204b-9630-4ae4-90cf-ce487a75db2b.png)

The new API supports a new argument `background_color` to the plotting functions:

```
hex_centers, _ = create_hex_grid(nx=5,
                                 ny=5,
                                 plotting_gap=0.05,
                                 min_diam=1,
                                 rotate_deg=5,
                                 face_color=[0.9, 0.1, 0.1, 0.05],
                                 do_plot=True,
                                 background_color=(0.8, 0.8, 0.8))
```

**Comment by masoudrahimi39** [comment]
Thank you. It is great.
