### ISSUE TITLE
Compatibility with numpy>=1.24

### ISSUE THREAD

**Issue by MBredlau** [alexkaz2/hexalattice#9]
It looks like hexalattice is not compatible with numpy version 1.24 and higher. There are problems with the declaration of np.float, which is deprecated in newer versions of numpy.

**Comment by alexkaz2** [comment]
Marvin thank you for letting me know.
I will update the module in the next few days, and close the issue once I am done.

**Comment by alexkaz2** [comment]
Hi Marvin,
I can't find a reference to np.float in the most current verion of Hexalattice.
Could you either point me to the problematic line in the code, or try to update the package and re-run your code?

Let me know how it works out
